config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  # devise_for :users
  # resources :products, :users, :sessions, :categories
  resources :products, :categories
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root "products#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true

  has_many :category_products
  has_many :products, through: :category_products

  belongs_to :product


end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base

  belongs_to :category
  belongs_to :product

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :quantity, presence: true

  has_many :category_products
  has_many :categories, through: :category_products
  has_many :order_items
  
  belongs_to :category

  # default_scope { where(active: true) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # protect_from_forgery with: :null_session
  helper_method :current_order
  
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/old-sessions_controller.rb
# class SessionsController < ApplicationController
#   def new
#   end

#   def create
#     @user = User.find_by(email: params["Email"])
#     password = params["Password"]
#       # if @user.admin && @user.authenticate(password)
#       #   session[:user_id] = @user.id
#       #   redirect_to '/admin'
#       if @user && @user.authenticate(password)
#         session[:user_id] = @user.id
#         flash[:success] = "You're logged in!"
#         redirect_to root_path
#       else
#         redirect_to root_path
#       end
#   end

#   def destroy
#     session.delete(:user_id)
#     redirect_to root_path
#   end
# end

app/controllers/old-users_controller.rb
# class UsersController < ApplicationController
#   def new
#     @user = User.new
#   end

#   def create
#     @user = User.new(user_params)
#     if @user.save
#       redirect_to root_path
#       SignupMailer.welcome_email(@user).deliver
#     else
#       redirect_to new_user_path
#     end
#   end

#   private
#   def user_params
#     params.require(:user).permit(:username, :email, :password)
#   end
# end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
  	@order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
  	@order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
    # respond_to do |format|
    #   format.html { respond_with @order } 
    #   format.js {}
    # end

  end

  def destroy
  	@order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :authenticate_admin, except: [:show, :index]
  # before_action :authenticate_user, except: [:show, :index]
  # before_filter :authenticate_user
  # before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @categories = Category.all
    @order_item = current_order.order_items.new
  end

  def show
    find_product
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new()
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      redirect_to 'products/new'
    end
  end

  def edit
    find_product
  end

  def update
    find_product
    successful_save = @product.update(product_params)
    if successful_save
      redirect_to product_path(@product)
    else
      redirect_to 'edit'
    end
  end

  def destroy
    find_product.destroy
    redirect_to root_path
  end

private
 #def authenticate_admin
 #  if current_user.admin
 #    redirect_to rails_admin
 #  else
 #    redirect_to root_path
 #  end
 #end

  def product_params
    params.require(:product).permit(:name, :price, :description, :quantity, :image)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", remote: true, class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.haml
%div{:class => "shopping-cart"}
= render partial:'shopping_cart'

app/views/categories/show.html.haml
.col-md-12
  =link_to "Home", root_path, {class: "btn btn-info"}

-if @product != nil
  .col-md-12
    #item
      #li
        %h3
        #span= @product.name
        =link_to image_tag(@product.image), product_path(@product)
      #li
        %strong Price:
        #span= number_to_currency(@product.price)
      #li
        %strong Description:
        #span= @product.description
      #li
        %strong Quantity:
        #span= @product.quantity
      -# #li
      -#   %strong Category:
      -#   #span= @product.category

- if @products != nil
  -@products.each do |p|
    .col-md-4
      #item
        #li
          %h3
          #span= p.name
          =link_to image_tag("#{p.image}"), product_path(p)
        #li
          %strong Price:
          #span= number_to_currency(p.price)
        #li
          %strong Description:
          #span= p.description
        #li
          %strong Quantity:
          #span= p.quantity
        -# #li
        -#   %strong Category:
        -#   #span= Category.find(p.category_id).name

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link", id: "cart" %>

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
      %meta{content: "IE=edge", "http-equiv": "X-UA-Compatible"}
        %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
          %meta{content: "", name: "description"}
            %meta{content: "", name: "author"}
              %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"}
              %link{href: "../../favicon.ico", rel: "icon"}
              %link{href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", rel: "stylesheet"}
                %title HAMAZON!
                = stylesheet_link_tag 'application', media: 'all'
                = csrf_meta_tags
                = javascript_include_tag 'application'
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: "/"} HAMZON
          %ul.nav.navbar-nav

          %li= ENV['USERNAME']

          - if user_signed_in?
            %li= link_to  "Sign Out", destroy_user_session_path, :method => :get
          - else

            %li= link_to "Sign Up", new_user_registration_path
            %li= link_to "Log In", new_user_session_path

          / # - if user_signed_in?
          / #   - if current_user.admin == true
          / #     %li= link_to "Log In", rails_admin


        .navbar-collapse
    / Main jumbotron for a primary marketing message or call to action
    %p.notice= notice
    %p.alert= alert
    .jumbotron
      .container
        %h1  HAMAZON
        %h1 
          = render partial: 'layouts/cart_text'
    .container
      .row
        = yield
      %hr
        %footer
          %p &copy; 2016 HAMAZON, Inc.
    / Placed at the end of the document so the pages load faster
    -# %script{src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"}
    -# :javascript
    -#   window.jQuery || document.write('<\/script>')

app/views/order_items/create.html.haml
%h1 OrderItems#create
%p Find me in app/views/order_items/create.html.haml

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $("#cart").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.haml
%h1 OrderItems#destroy
%p Find me in app/views/order_items/destroy.html.haml

app/views/order_items/destroy.js.erb
$("#cart").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".row").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.haml
%h1 OrderItems#update
%p Find me in app/views/order_items/update.html.haml

app/views/order_items/update.js.erb
$("#cart").html("<%= j render(:partial => 'layouts/cart_text') %>")
$(".row").html("<%= j render(:partial => 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.hidden_field :quantity, value: 1  %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

app/views/products/_productinfo.html.haml
= form_for @product do |f|
  =f.label :name
  =f.text_field :name
  =f.label :price
  =f.text_field :price
  =f.label :description
  =f.text_field :description
  =f.label :quantity
  =f.text_field :quantity
  =f.label :image
  =f.text_field :image
  = f.submit
=link_to "Home", root_path

app/views/products/edit.html.haml
= render partial:'productinfo'

app/views/products/index.html.haml
-if flash[:success]
  .alert.alert-info
    %p= flash[:success]
-elsif flash[:danger]
  .alert.alert-danger
    %p= flash[:danger]

.col-md-12
  -@categories.each do |cat|
    =link_to cat.name.capitalize, category_path(cat), {class: "btn btn-info"}

-@products.each do |p|
  .col-md-4
    #item
      #li
        %h3
        #span= p.name
        = link_to image_tag("#{p.image}"), product_path(p)
      #li
        %strong Price:
        #span= number_to_currency(p.price)
      #li
        %strong Description:
        #span= p.description
      #li
        %strong Quantity:
        #span= p.quantity
      #li
        = render :partial => 'product_row', :locals => { :product => p, :order_item => @order_item }
      -# #li
      -#   %strong Category:
      -#   #span= Category.find(p.category_id).name

app/views/products/new.html.haml
= render partial:'productinfo'

app/views/products/show.html.haml
=link_to "Home", root_path
#li
  %h3
    %strong
      #span= @product.name
=image_tag("#{@product.image}")
#li
  %strong Price:
#span= number_to_currency(@product.price)
#li
  %strong Description:
#span= @product.description
#li
  %strong Quantity:
#span= @product.quantity
#li
  %strong Category:

- @product.categories.each do |c|
  = c.name
  %br

app/views/users/new.html.haml
= form_for @user, html: {class: "navbar-form full-width"} do |f|
  - if @user.errors.any?
    %div.error_messages
      %h2 Form is invalid
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  = f.label :email, 'Email:'
  = f.text_field :email, class: "form-control"
  %br

  = f.label :username, 'Username:'
  = f.text_field :username, class: "form-control"
  %br

  = f.label :password, 'Password:'
  = f.text_field :password, class: "form-control", type: "password"
  %br

  = f.submit 'Sign Up', class: "btn btn-warning"

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>